### ISSUE TITLE
glob mismatch between artifacts_path and plugin

### ISSUE THREAD

**Issue by ineffyble** [buildkite-plugins/artifacts-buildkite-plugin#26]
So in one step I have 
```
    artifact_paths:
      - "htv/build/**/*"
```

When the job runs, 25 files are picked up, including htv/build/index.html, and files inside htv/build/static/.

In a later step, I have 
```
      artifacts#v1.2.0:
        download: "htv/build/**/*"
```

This only finds 20 files - the ones in the /static/ subfolder.

**Comment by ineffyble** [comment]
Ah, I see this is actually agent behaviour. Closing.

**Comment by lox** [comment]
Yeah, sorry @ineffyble. We'd love to fix this at some point, but it's expected in lots of places.
