### ISSUE TITLE
Does upload and download maintain permissions

### ISSUE THREAD

**Issue by ipinak** [buildkite-plugins/artifacts-buildkite-plugin#40]
Hi,

I'm uploading some artifacts and I want to know whether the file permissions will be maintained when I download the same artifacts on a later step. From what I've noticed file permissions are not maintained.

Version: artifacts 1.2.0
OS of agent: Linux ubuntu

**Comment by keithduncan** [comment]
Hi @ipinak I’m afraid that’s true, `artifacts` are stored in S3 or the storage system of your choosing when configuring the Buildkite Agent. The best way to maintain UNIX file system permissions across artifact upload/download is to create a `tar` archive which supports this metadata, and upload as your artifact instead :bow:

**Comment by ipinak** [comment]
Thanks for update I will consider that. 
👍
