### ISSUE TITLE
Allow specifying step per artifact

### ISSUE THREAD

**Issue by DuBistKomisch** [buildkite-plugins/artifacts-buildkite-plugin#47]
You can currently only specify a `step` for all downloads, not individually. Workaround is to list the plugin multiple times, but that's a bit clunky. It would be nice to be able to have something like a `step` key like `from` and `to`.

**Comment by pzeballos** [comment]
Hey @DuBistKomisch! sorry for the long delay! 😅 This is a good idea!
Are you still interested in this functionality, If so, would you like to submit a PR? we'll be happy to review it! 😊

**Comment by DuBistKomisch** [comment]
Thanks, if I run into this problem again, I think I will take a shot at it.

A do have a PR open on another plugin I would like reviewed if you guys get a chance though: https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/pull/244

**Comment by pzeballos** [comment]
Thanks @DuBistKomisch! We are organizing the workload on all our plugins (we didn't have the capacity), so you'll probably get a response on the PR in the followings weeks.
