### ISSUE TITLE
Option to not fail if there are no artifacts to download

### ISSUE THREAD

**Issue by TSMMark** [buildkite-plugins/artifacts-buildkite-plugin#56]
This plugin exit 1 failure status when no artifacts are found matching the pattern.

However, my workflow conditionally uploads artifacts, only under certain circumstances — So there will not always be artifacts to download. 

How can I configure the plugin to not fail when there are no results?

Example from my pipeline:

Downloading artifacts | 0s
-- | --
  | [2020-10-22T19:22:59Z] 2020-10-22 19:22:59 INFO   Searching for artifacts: "*"
  | [2020-10-22T19:22:59Z] 2020-10-22 19:22:59 FATAL  Failed to download artifacts: No artifacts found for downloading
  | [2020-10-22T19:22:59Z] 🚨 Error: The plugin artifacts pre-command hook exited with status 1
  |  

I'm open to submitting a PR if this is not supported yet

**Comment by TSMMark** [comment]
Looks like the error is coming from the internals of the command: `buildkite-agent artifact download`

https://github.com/buildkite/agent/blob/cc5e8ab70d3994130d0a68b0b50d2aba5f557cc7/agent/artifact_downloader.go#L77

**Comment by chrissav** [comment]
Ran into this same problem.  @TSMMark Did you find a way around it?

**Comment by pzeballos** [comment]
Hey folks! Because this is the default behavior of the command `buildkite artifact download`, the plugin should follow the same design. You can write your own script which does the artifact download and the error handling case in there. 
Thanks!

**Comment by pzeballos** [comment]
Hey folks 👋🏻 we are revisiting this one, and while we are not going to change the default behavior, we'll work on a new option that you can turn on/off.
