### ISSUE TITLE
Add skip-on-canceled option

### ISSUE THREAD

**Issue by ngan** [buildkite-plugins/artifacts-buildkite-plugin#78]
Canceled builds still run the artifacts plugin to upload logs. It would be cool if there was an option to skip uploading if the build was canceled. This would help us save lots of space in our S3 bucket.

**Comment by toote** [comment]
@ngan that is quite an interesting use case. Unfortunately, there is no way to be sure if a step was cancelled or not (it depends both on agent configuration and step specifics)... but that doesn't mean that there is no solution.

I just created a more general feature in which you can specify what step exit codes you want to skip uploads for. Do you think that would fit what you need?
